# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.x'
  displayName: 'Install Node.js'

- script: |
    npm i
    npm run build
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'build project'

- script: |
    npm run semantic-release
  displayName: 'run semantic release'